sudo: false

language: php

php:
  - '7.2'
  - '7.3'

cache:
 directories:
   - $HOME/.composer/cache/files

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

notifications:
  email: false
